name = "thegarden"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "thegarden-db"
database_id = "b6c4ef3c-3b11-445e-8cc0-9cb92e5efee4"

[[kv_namespaces]]
binding = "SETTINGS"
id = "f914b3334817405bae6854a30625a0bc"
preview_id = "287ee85e00b04bd2893ae7e50eef8186"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "thegarden-photos"
